{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "surya-ocr.fullname" . }}-pdf
  labels:
    {{- include "surya-ocr.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.pdf.accessMode }}
  {{- if .Values.persistence.pdf.storageClass }}
  {{- if (eq "-" .Values.persistence.pdf.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.pdf.storageClass }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.pdf.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "surya-ocr.fullname" . }}-uploads
  labels:
    {{- include "surya-ocr.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.uploads.accessMode }}
  {{- if .Values.persistence.uploads.storageClass }}
  {{- if (eq "-" .Values.persistence.uploads.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.uploads.storageClass }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
{{- end }} 